import type { Thinker } from "@/types/content";

/**
 * Twenty-nine representative thinkers across traditions, chosen to cover
 * the site's recurring questions. Quotes appear only where reliably
 * sourced and commonly translated; otherwise `idea` carries a faithful
 * summary of a characteristic view.
 */
export const thinkers: Thinker[] = [
  {
    id: "socrates",
    name: "Socrates",
    birth: -470,
    death: -399,
    approximate: false,
    region: "europe",
    placeLabel: "Athens",
    tradition: "greek",
    summary:
      "The barefoot gadfly of Athens who made philosophy a practice of relentless questioning rather than a body of doctrine.",
    coreIdeas: [
      "The unexamined life is not worth living",
      "Knowing that you do not know is the beginning of wisdom",
      "Virtue is knowledge: no one does wrong willingly",
    ],
    questions: ["how-should-i-live", "what-is-knowledge", "what-is-justice"],
    works: ["(Dialogues of Plato, as character)"],
    relatedThinkers: ["plato", "epictetus", "confucius"],
    historicalContext:
      "Athens at its imperial height and in its wounded decline: war lost, plague survived, democracy twitchy about critics. Socrates' trial in 399 BCE made the cost of honest questioning permanent.",
    quote: {
      text: "The unexamined life is not worth living.",
      source: "Plato, Apology 38a",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Socrates" }],
  },
  {
    id: "plato",
    name: "Plato",
    birth: -428,
    death: -348,
    approximate: true,
    region: "europe",
    placeLabel: "Athens",
    tradition: "greek",
    summary:
      "Socrates' student who turned questioning into a system — and founded the West's first school in the process.",
    coreIdeas: [
      "Reality has two levels: fleeting appearances and eternal Forms",
      "Education is turning the soul toward what is real, not filling a vessel",
      "The just soul and the just city have the same structure",
    ],
    questions: ["what-is-real", "what-is-knowledge", "what-is-justice"],
    works: ["Republic", "Symposium", "Phaedo", "Apology"],
    relatedThinkers: ["socrates", "aristotle", "ibn-sina"],
    historicalContext:
      "Wrote through the fourth century BCE, a generation after Athens' defeat, trying to found politics and knowledge on something steadier than opinion.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Plato" }],
  },
  {
    id: "aristotle",
    name: "Aristotle",
    birth: -384,
    death: -322,
    approximate: false,
    region: "europe",
    placeLabel: "Stagira, Athens",
    tradition: "greek",
    summary:
      "The systematizer: logic, biology, ethics, politics, poetics — Aristotle organized knowledge into fields and investigated each one empirically.",
    coreIdeas: [
      "Flourishing (eudaimonia) is activity of the soul in accordance with virtue",
      "We are what we repeatedly do: virtue is habituated, not decreed",
      "Everything strives toward its proper fulfillment",
    ],
    questions: ["how-should-i-live", "what-is-justice", "what-is-the-good-life"],
    works: ["Nicomachean Ethics", "Politics", "Metaphysics"],
    relatedThinkers: ["plato", "ibn-sina", "ibn-rushd"],
    historicalContext:
      "Plato's student, Alexander's teacher, and the Lyceum's founder — working when Greek science and the fresh income of empire made encyclopedic curiosity possible.",
    quote: {
      text: "We are what we repeatedly do.",
      source: "Nicomachean Ethics (paraphrase of Book II; popularly attributed)",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Aristotle" }],
  },
  {
    id: "zhuangzi",
    name: "Zhuangzi",
    birth: -369,
    death: -286,
    approximate: true,
    region: "east-asia",
    placeLabel: "State of Song, China",
    tradition: "daoist",
    summary:
      "The Daoist skeptic who used jokes, dreams and fables to loosen the grip of fixed categories.",
    coreIdeas: [
      "Perspective determines what seems real",
      "Usefulness may lie in uselessness",
      "Skill at its highest is effortless — the butcher's blade finds the joints",
    ],
    questions: ["what-is-real", "how-should-i-live", "what-am-i"],
    works: ["Zhuangzi"],
    relatedThinkers: ["laozi", "nagarjuna", "dogen"],
    historicalContext:
      "The Warring States era made Confucian careerism deadly; Zhuangzi's answer was to decline every official post and write of free wandering instead.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Zhuangzi" }],
  },
  {
    id: "buddha",
    name: "The Buddha",
    birth: -563,
    death: -483,
    approximate: true,
    region: "south-asia",
    placeLabel: "Lumbini / Ganges valley",
    tradition: "buddhist",
    summary:
      "A former prince whose diagnosis of suffering — and prescription of attention — became one of the world's great traditions of practice.",
    coreIdeas: [
      "Suffering arises from craving, and craving can be understood",
      "The self is a process, not a possession",
      "Attention (mindfulness) can be trained like strength",
    ],
    questions: ["what-is-suffering", "what-am-i", "how-should-i-live"],
    relatedThinkers: ["nagarjuna", "dogen", "epictetus"],
    historicalContext:
      "Taught in the Ganges plain in the fifth century BCE, in the same ferment of wandering teachers that produced the Upanishads and Mahavira.",
    sources: [{ title: "Encyclopædia Britannica — Buddha" }],
  },
  {
    id: "nagarjuna",
    name: "Nagarjuna",
    birth: 150,
    death: 250,
    approximate: true,
    region: "south-asia",
    placeLabel: "Southern India",
    tradition: "buddhist",
    summary:
      "The master of Madhyamaka dialectic who used strict logic to dissolve every fixed position, including his own.",
    coreIdeas: [
      "All things are empty (śūnya) of independent, permanent essence",
      "Emptiness is not nihilism: things exist relationally",
      "Clinging to any view, even emptiness, is the error",
    ],
    questions: ["what-is-real", "what-am-i", "what-is-suffering"],
    works: ["Mūlamadhyamakakārikā"],
    relatedThinkers: ["buddha", "zhuangzi", "dogen"],
    historicalContext:
      "Wrote when Buddhism had become a scholastic empire; his tetralemma arguments were philosophy as scalpel, cutting conceptual grasping.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Nāgārjuna" }],
  },
  {
    id: "confucius",
    name: "Confucius",
    birth: -551,
    death: -479,
    approximate: false,
    region: "east-asia",
    placeLabel: "State of Lu, China",
    tradition: "confucian",
    summary:
      "The teacher of cultivated relationships whose vision of order through virtue organized East Asian life for millennia.",
    coreIdeas: [
      "Do not impose on others what you do not wish for yourself",
      "Ritual and music shape character more than commands",
      "The ruler's example is stronger than the ruler's law",
    ],
    questions: ["how-should-i-live", "what-is-justice", "what-is-the-good-life"],
    works: ["Analects"],
    relatedThinkers: ["laozi", "zhuangzi", "aristotle"],
    historicalContext:
      "A minor official and lifelong teacher in the chaotic sixth century BCE, convinced that the answer to disorder was education, not conquest.",
    quote: {
      text: "Do not do to others what you do not want done to yourself.",
      source: "Analects 15:24",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Confucius" }],
  },
  {
    id: "laozi",
    name: "Laozi",
    birth: -600,
    death: -400,
    approximate: true,
    region: "east-asia",
    placeLabel: "Chu, China (traditional)",
    tradition: "daoist",
    summary:
      "The legendary author of the Daodejing, the short book of water-soft wisdom that counterweights every system-builder.",
    coreIdeas: [
      "The softest things overcome the hardest",
      "Governing well means governing lightly",
      "Names and categories are useful but never final",
    ],
    questions: ["how-should-i-live", "what-is-real", "what-is-the-good-life"],
    works: ["Daodejing (attributed)"],
    relatedThinkers: ["zhuangzi", "confucius", "dogen"],
    historicalContext:
      "Whether one sage or a school's collected voice, the Daodejing speaks from the same war-torn centuries as Confucius — and recommends the opposite politics.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Daoism" }],
  },
  {
    id: "zoroaster",
    name: "Zoroaster",
    birth: -1000,
    death: -600,
    approximate: true,
    region: "persia",
    placeLabel: "Iranian plateau",
    tradition: "persian",
    summary:
      "The prophet of the Iranian plateau whose vision of truth against falsehood shaped Persian religion and, indirectly, the Abrahamic ones.",
    coreIdeas: [
      "Existence is a moral struggle: truth (asha) against the lie (druj)",
      "Thoughts, words and deeds are the three registers of the battle",
      "The good mind (vohu manah) can be cultivated",
    ],
    questions: ["what-is-the-good-life", "what-is-suffering", "how-should-i-live"],
    works: ["Gathas"],
    relatedThinkers: ["rumi", "suhrawardi", "khayyam"],
    historicalContext:
      "Dating is contested — anywhere from the second millennium BCE to the sixth — but his hymns are among humanity's oldest surviving poetry of moral choice.",
    sources: [{ title: "Encyclopædia Iranica — Zarathustra" }],
  },
  {
    id: "rumi",
    name: "Rumi",
    birth: 1207,
    death: 1273,
    approximate: false,
    region: "persia",
    placeLabel: "Balkh → Konya",
    tradition: "sufi",
    summary:
      "The Sufi poet whose meeting with Shams of Tabriz turned a jurist into a poet of ecstatic, searching love.",
    coreIdeas: [
      "Love is the force that dissolves the separate self",
      "The wound is the place where the light enters",
      "Beyond right and wrong there is a field — meet there",
    ],
    questions: ["what-am-i", "what-is-suffering", "how-should-i-live"],
    works: ["Masnavi", "Divan-e Shams"],
    relatedThinkers: ["shams-tabrizi", "al-ghazali", "attar"],
    historicalContext:
      "Persia under Mongol shock: Rumi's family fled Balkh ahead of the armies, settling in Konya, where a wandering dervish rearranged his life.",
    quote: {
      text: "Beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.",
      source: "Divan-e Shams (as popularly translated; A. Arberry's translations vary)",
    },
    sources: [{ title: "Encyclopædia Iranica — Rumi" }],
  },
  {
    id: "shams-tabrizi",
    name: "Shams of Tabriz",
    birth: 1185,
    death: 1248,
    approximate: true,
    region: "persia",
    placeLabel: "Tabriz → Konya",
    tradition: "sufi",
    summary:
      "The itinerant dervish who became Rumi's mirror — forty days of conversation that produced forty thousand lines of poetry.",
    coreIdeas: [
      "The teacher appears when the student is ready to be undone",
      "Direct experience outranks book learning",
      "Love is the shortest path to truth",
    ],
    questions: ["what-am-i", "how-should-i-live"],
    works: ["Maqalat (discourses)"],
    relatedThinkers: ["rumi", "attar", "al-ghazali"],
    historicalContext:
      "Shams disappears from the record around 1247; Rumi's search for him became the Divan's engine.",
    sources: [{ title: "Encyclopædia Iranica — Shams-e Tabrizi" }],
  },
  {
    id: "attar",
    name: "Attar of Nishapur",
    birth: 1145,
    death: 1221,
    approximate: true,
    region: "persia",
    placeLabel: "Nishapur",
    tradition: "sufi",
    summary:
      "The apothecary-poet of Nishapur whose Conference of the Birds maps the soul's journey through seven valleys to its own king.",
    coreIdeas: [
      "The journey's end is a mirror: what the birds sought was themselves",
      "Suffering is the price of the valleys — and their medicine",
      "Stories are ladders; climb and discard",
    ],
    questions: ["how-should-i-live", "what-is-suffering", "what-am-i"],
    works: ["Conference of the Birds", "Ilahi-Nama"],
    relatedThinkers: ["rumi", "shams-tabrizi", "al-ghazali"],
    historicalContext:
      "Died in the Mongol sack of Nishapur (1221), leaving the Sufi allegory perfected for Rumi to inherit.",
    sources: [{ title: "Encyclopædia Iranica — ʿAṭṭār" }],
  },
  {
    id: "ibn-sina",
    name: "Ibn Sina (Avicenna)",
    birth: 980,
    death: 1037,
    approximate: false,
    region: "persia",
    placeLabel: "Bukhara → Isfahan",
    tradition: "islamic",
    summary:
      "The physician-philosopher of the Islamic golden age whose Canon taught medicine for six centuries and whose 'floating man' argued the soul knows itself directly.",
    coreIdeas: [
      "The soul is aware of itself even suspended from all sensation",
      "Necessity and existence must be distinguished — essence is not existence",
      "Medicine is a science of principles, not a bag of recipes",
    ],
    questions: ["what-am-i", "what-is-real", "what-is-knowledge"],
    works: ["The Canon of Medicine", "The Book of Healing"],
    relatedThinkers: ["aristotle", "al-ghazali", "suhrawardi"],
    historicalContext:
      "A polymath courtier in the turbulent Iranian principalities — writing between patrons, in hiding, and in prison, dying at 57 with the medieval world's textbooks in hand.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Avicenna" }],
  },
  {
    id: "al-ghazali",
    name: "Al-Ghazali",
    birth: 1058,
    death: 1111,
    approximate: false,
    region: "persia",
    placeLabel: "Tus, Persia",
    tradition: "sufi",
    summary:
      "The jurist who dismantled certainty, resigned Baghdad's finest teaching post, and rebuilt knowledge from direct experience.",
    coreIdeas: [
      "Sense-perception and reason both deceive; certainty needs another ground",
      "Philosophy's demonstrations cannot prove what they claim",
      "Skepticism honestly followed can end in trust, not despair",
    ],
    questions: ["what-is-knowledge", "how-should-i-live", "what-is-real"],
    works: ["Deliverance from Error", "Incoherence of the Philosophers"],
    relatedThinkers: ["ibn-sina", "descartes", "rumi"],
    historicalContext:
      "His crisis of 1095 — he could no longer trust his own teaching — led to a decade of wandering and a book that anticipated Descartes' methodic doubt by five centuries.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Al-Ghazali" }],
  },
  {
    id: "khayyam",
    name: "Omar Khayyam",
    birth: 1048,
    death: 1131,
    approximate: false,
    region: "persia",
    placeLabel: "Nishapur",
    tradition: "persian",
    summary:
      "The mathematician who solved cubic equations geometrically, reformed the calendar, and wrote skeptical quatrains about fate and the present moment.",
    coreIdeas: [
      "The present is the only possession: the rest is memory or guess",
      "Doubt is honest when certainty is unavailable",
      "Mathematics and poetry can ask the same questions",
    ],
    questions: ["how-should-i-live", "what-can-i-control", "what-is-suffering"],
    works: ["Rubaiyat", "Treatise on Demonstration of Problems of Algebra"],
    relatedThinkers: ["rumi", "zhuangzi", "al-ghazali"],
    historicalContext:
      "Worked at Isfahan under Malik-Shah's patronage, then outlived the court's collapse — the quatrains read differently after patronage ends.",
    quote: {
      text: "Be happy for this moment. This moment is your life.",
      source: "Rubaiyat (FitzGerald translation tradition; attributed in Persian sources)",
    },
    sources: [{ title: "Encyclopædia Iranica — ʿOmar Khayyām" }],
  },
  {
    id: "suhrawardi",
    name: "Suhrawardi",
    birth: 1154,
    death: 1191,
    approximate: false,
    region: "persia",
    placeLabel: "Sohrevard → Aleppo",
    tradition: "sufi",
    summary:
      "The 'shaykh of illumination' who rebuilt philosophy around light and intuitive knowledge — and was executed at 37 for the trouble.",
    coreIdeas: [
      "Reality is graded light; darkness is mere absence",
      "Knowledge by presence (direct intuition) outranks definition",
      "Persian and Greek wisdom are one tradition, reunited",
    ],
    questions: ["what-is-real", "what-is-knowledge", "what-am-i"],
    works: ["The Philosophy of Illumination"],
    relatedThinkers: ["ibn-sina", "al-ghazali", "rumi"],
    historicalContext:
      "Wrote in Aleppo under Saladin's circle; the jurists' charge of heterodox philosophy ended a career that redefined Persian philosophy.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Suhrawardi" }],
  },
  {
    id: "ibn-rushd",
    name: "Ibn Rushd (Averroes)",
    birth: 1126,
    death: 1198,
    approximate: false,
    region: "middle-east",
    placeLabel: "Cordoba",
    tradition: "islamic",
    summary:
      "The Cordoban jurist who defended philosophy against al-Ghazali's critique and carried Aristotle back into Europe's future.",
    coreIdeas: [
      "Demonstration, dialectic and rhetoric are valid paths for different minds",
      "Truth does not contradict truth",
      "Society flourishes when it protects thinking people",
    ],
    questions: ["what-is-knowledge", "what-is-justice", "what-is-real"],
    works: ["The Incoherence of the Incoherence", "Aristotle commentaries"],
    relatedThinkers: ["aristotle", "al-ghazali", "ibn-sina"],
    historicalContext:
      "A judge and physician at the Almohad court; banished briefly near his death, his Latin translations sparked Europe's Aristotelian revival.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Averroes" }],
  },
  {
    id: "ibn-khaldun",
    name: "Ibn Khaldun",
    birth: 1332,
    death: 1406,
    approximate: false,
    region: "africa",
    placeLabel: "Tunis → Cairo",
    tradition: "islamic",
    summary:
      "The North African historian who founded a science of civilization — solidarity, economics and the life cycles of states.",
    coreIdeas: [
      "Group solidarity (asabiyya) is the engine that builds and breaks states",
      "Civilizations have lifecycles, not just chronicles",
      "Economics and morality are intertwined: unjust taxation destroys prosperity",
    ],
    questions: ["what-is-justice", "how-should-i-live"],
    works: ["Muqaddimah", "Book of Lessons"],
    relatedThinkers: ["thucydides", "aristotle", "al-ghazali"],
    historicalContext:
      "A career diplomat and scholar who survived plagues, sieges and prison — and twice met the conqueror Tamerlane in camp, an encounter he wrote up like a researcher.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Ibn Khaldun" }],
  },
  {
    id: "thucydides",
    name: "Thucydides",
    birth: -460,
    death: -400,
    approximate: true,
    region: "europe",
    placeLabel: "Athens",
    tradition: "greek",
    summary:
      "The exiled general who wrote the Peloponnesian War as a possession forever — power, fear and miscalculation stripped of myth.",
    coreIdeas: [
      "Necessity of nature: the strong do what they can, the weak suffer what they must",
      "Words change meaning in civil war",
      "Human nature repeats; history is not one-off",
    ],
    questions: ["what-is-justice", "how-should-i-live"],
    works: ["History of the Peloponnesian War"],
    relatedThinkers: ["herodotus", "socrates", "ibn-khaldun"],
    historicalContext:
      "An Athenian commander exiled after losing Amphipolis in 424 BCE; exile gave him sources on both sides and time to think.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Thucydides" }],
  },
  {
    id: "herodotus",
    name: "Herodotus",
    birth: -484,
    death: -425,
    approximate: true,
    region: "europe",
    placeLabel: "Halicarnassus",
    tradition: "greek",
    summary:
      "The traveler-historian who recorded other cultures on their own terms — inquiry, not conquest, as a way of knowing.",
    coreIdeas: [
      "Custom is king of all: each culture finds its own ways natural",
      "Verify, compare, and say what you were told",
      "Greatness invites the scrutiny of time",
    ],
    questions: ["what-is-knowledge", "how-should-i-live"],
    works: ["The Histories"],
    relatedThinkers: ["thucydides", "socrates", "ibn-khaldun"],
    historicalContext:
      "A Greek of Persian-ruled Caria, writing while Athens' empire was young — curious about the 'barbarians' it was fighting.",
    sources: [{ title: "Britannica — Herodotus" }],
  },
  {
    id: "epictetus",
    name: "Epictetus",
    birth: 50,
    death: 135,
    approximate: true,
    region: "europe",
    placeLabel: "Hierapolis → Rome → Nicopolis",
    tradition: "stoic",
    summary:
      "Born enslaved, lamed by a master, free at last — the Stoic teacher who made the dichotomy of control the core of a usable philosophy.",
    coreIdeas: [
      "Some things are up to us, some are not; peace lies in knowing which",
      "It is not events that disturb us, but our judgments about them",
      "Practice like an athlete: small, repeated, under load",
    ],
    questions: ["what-can-i-control", "how-should-i-live", "what-is-suffering"],
    works: ["Discourses", "Enchiridion"],
    relatedThinkers: ["marcus-aurelius", "seneca", "buddha"],
    historicalContext:
      "Taught in Rome until Domitian banished the philosophers (c. 93 CE), then founded a school in Nicopolis; his student Arrian published the notes we read now.",
    quote: {
      text: "It's not what happens to you, but how you react to it that matters.",
      source: "Enchiridion (paraphrase of ch. 5)",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Epictetus" }],
  },
  {
    id: "seneca",
    name: "Seneca",
    birth: -4,
    death: 65,
    approximate: false,
    region: "europe",
    placeLabel: "Cordoba → Rome",
    tradition: "stoic",
    summary:
      "Stoic philosopher, essayist and — uncomfortably — Nero's tutor and fixer, whose letters on time, anger and wealth are written from inside the tension.",
    coreIdeas: [
      "We are not given a short life; we make it short",
      "We suffer more in imagination than in reality",
      "Wealth is the ability to fully experience the present",
    ],
    questions: ["how-should-i-live", "what-can-i-control", "what-is-time"],
    works: ["Letters to Lucilius", "On the Shortness of Life"],
    relatedThinkers: ["epictetus", "marcus-aurelius", "rumi"],
    historicalContext:
      "Exiled, recalled to tutor Nero, complicit in the regime's crimes, ordered to die in 65 CE — his calm prose has been argued about ever since.",
    quote: {
      text: "It is not that we have a short time to live, but that we waste a lot of it.",
      source: "On the Shortness of Life, ch. 1",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Seneca" }],
  },
  {
    id: "marcus-aurelius",
    name: "Marcus Aurelius",
    birth: 121,
    death: 180,
    approximate: false,
    region: "europe",
    placeLabel: "Rome",
    tradition: "stoic",
    summary:
      "Emperor of a war-torn empire who wrote private notes to himself — the most powerful man's reminders to stay decent.",
    coreIdeas: [
      "You have power over your mind, not outside events",
      "The obstacle is the way: what blocks the action advances it",
      "Do the work of a human being, and accept what is not yours to decide",
    ],
    questions: ["what-can-i-control", "how-should-i-live", "what-is-time"],
    works: ["Meditations"],
    relatedThinkers: ["epictetus", "seneca", "confucius"],
    historicalContext:
      "Ruled 161–180 through plague and endless frontier war; the Meditations were written in army camps, in Greek, for an audience of one.",
    quote: {
      text: "You have power over your mind — not outside events. Realize this, and you will find strength.",
      source: "Meditations (popular compilation of Med. 8.8 / 12.22 themes)",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Marcus Aurelius" }],
  },
  {
    id: "shankara",
    name: "Adi Shankara",
    birth: 700,
    death: 750,
    approximate: true,
    region: "south-asia",
    placeLabel: "Kerala → Himalaya",
    tradition: "vedanta",
    summary:
      "The nondualist reformer who traveled India founding monasteries and arguing that only consciousness is ultimately real.",
    coreIdeas: [
      "Brahman alone is real; the world of separation is appearance",
      "The self (atman) is not other than the absolute (brahman)",
      "Liberation is recognition, not acquisition",
    ],
    questions: ["what-is-real", "what-am-i", "what-is-suffering"],
    works: ["Brahma Sutra Bhashya", "Vivekachudamani"],
    relatedThinkers: ["nagarjuna", "buddha", "suhrawardi"],
    historicalContext:
      "By tradition died at 32 after walking the subcontinent; the four monastic centers he founded still anchor Hindu monasticism.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Advaita Vedanta" }],
  },
  {
    id: "dogen",
    name: "Dōgen",
    birth: 1200,
    death: 1253,
    approximate: false,
    region: "east-asia",
    placeLabel: "Kyoto → Song China → Eiheiji",
    tradition: "zen",
    summary:
      "The founder of Japanese Sōtō Zen, who returned from China to teach that practice is not a means to enlightenment — it is enlightenment, enacted.",
    coreIdeas: [
      "Practice and realization are one (shushō ittō)",
      "To study the self is to forget the self",
      "Time is being: each moment is complete",
    ],
    questions: ["what-am-i", "what-is-time", "how-should-i-live"],
    works: ["Shōbōgenzō", "Fukanzazengi"],
    relatedThinkers: ["buddha", "nagarjuna", "zhuangzi"],
    historicalContext:
      "Orphaned young, he crossed to Song China for authentic teaching, brought back Caodong/ Sōtō zazen, and wrote one of Buddhism's deepest philosophical works in Japanese.",
    quote: {
      text: "To study the Buddha Way is to study the self. To study the self is to forget the self.",
      source: "Genjōkōan (Shōbōgenzō)",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Dōgen" }],
  },
  {
    id: "descartes",
    name: "René Descartes",
    birth: 1596,
    death: 1650,
    approximate: false,
    region: "europe",
    placeLabel: "France → Netherlands",
    tradition: "enlightenment",
    summary:
      "The doubter who rebuilt knowledge from the certainty of a thinking self — and set philosophy's mind-body problem in motion.",
    coreIdeas: [
      "Doubt everything that can be doubted; keep only the indubitable",
      "I think, therefore I am",
      "Mind and body are distinct substances",
    ],
    questions: ["what-is-knowledge", "what-am-i", "what-is-real"],
    works: ["Meditations on First Philosophy", "Discourse on Method"],
    relatedThinkers: ["al-ghazali", "spinoza", "kant"],
    historicalContext:
      "A soldier-engineer-mathematician who did his best thinking in bed and in the Dutch Republic's quiet — publishing the Meditations in 1641, with objections and replies appended.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Descartes" }],
  },
  {
    id: "spinoza",
    name: "Baruch Spinoza",
    birth: 1632,
    death: 1677,
    approximate: false,
    region: "europe",
    placeLabel: "Amsterdam",
    tradition: "enlightenment",
    summary:
      "The lens-grinder excommunicated by his synagogue at 23, who argued that God and nature are one substance and that freedom is understanding necessity.",
    coreIdeas: [
      "There is one substance: God, or nature",
      "Freedom is not escaping causality but understanding it",
      "Emotions can be examined and re-ordered like ideas",
    ],
    questions: ["what-is-real", "what-is-freedom", "what-am-i"],
    works: ["Ethics", "Theological-Political Treatise"],
    relatedThinkers: ["descartes", "hume", "nietzsche"],
    historicalContext:
      "Cherem (ban) in 1656, then a quiet life grinding lenses in The Hague — living the modest, examined life his Ethics recommends.",
    quote: {
      text: "Do not weep; do not wax indignant. Understand.",
      source: "attributed maxim, reported by later writers",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Spinoza" }],
  },
  {
    id: "hume",
    name: "David Hume",
    birth: 1711,
    death: 1776,
    approximate: false,
    region: "europe",
    placeLabel: "Edinburgh",
    tradition: "enlightenment",
    summary:
      "The cheerful skeptic who found no self under introspection and no necessity behind causation — only habit.",
    coreIdeas: [
      "Reason is, and ought only to be, the slave of the passions",
      "Causation is expectation built from repeated experience",
      "The 'self' is a bundle of perceptions, not a thing",
    ],
    questions: ["what-am-i", "what-is-knowledge", "what-is-real"],
    works: ["A Treatise of Human Nature", "Enquiry Concerning Human Understanding"],
    relatedThinkers: ["spinoza", "kant", "buddha"],
    historicalContext:
      "His first book sank 'from the press'; his History paid the bills. Kant later credited Hume with interrupting his dogmatic slumber.",
    quote: {
      text: "A wise man proportions his belief to the evidence.",
      source: "Enquiry Concerning Human Understanding, §10",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Hume" }],
  },
  {
    id: "kant",
    name: "Immanuel Kant",
    birth: 1724,
    death: 1804,
    approximate: false,
    region: "europe",
    placeLabel: "Königsberg",
    tradition: "enlightenment",
    summary:
      "The punctual professor who synthesized empiricism and rationalism: we know appearances structured by our own minds — and morality begins with duty.",
    coreIdeas: [
      "The mind actively structures experience; we know things as they appear",
      "Act only on maxims you could will as universal law",
      "Treat humanity, in yourself and others, always as an end",
    ],
    questions: ["what-is-knowledge", "what-is-justice", "what-is-freedom"],
    works: ["Critique of Pure Reason", "Groundwork of the Metaphysics of Morals"],
    relatedThinkers: ["hume", "descartes", "nietzsche"],
    historicalContext:
      "Never traveled far from Königsberg, yet reordered the world of ideas — writing quietly through the era of revolution his ethics quietly endorsed.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Kant" }],
  },
  {
    id: "kierkegaard",
    name: "Søren Kierkegaard",
    birth: 1813,
    death: 1855,
    approximate: false,
    region: "europe",
    placeLabel: "Copenhagen",
    tradition: "existentialist",
    summary:
      "The Danish writer who insisted that existence is chosen, not deduced — anxiety as the dizziness of freedom.",
    coreIdeas: [
      "Subjectivity is truth: the deepest truths are lived, not proven",
      "Anxiety is the dizziness of freedom",
      "The crowd is untruth",
    ],
    questions: ["what-is-freedom", "how-should-i-live", "what-am-i"],
    works: ["Fear and Trembling", "Either/Or", "The Sickness Unto Death"],
    relatedThinkers: ["nietzsche", "de-beauvoir", "arendt"],
    historicalContext:
      "Wrote under a carousel of pseudonyms in golden-age Copenhagen, broke an engagement, and burned his inheritance on polemics — dead at 42, famous posthumously.",
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Kierkegaard" }],
  },
  {
    id: "nietzsche",
    name: "Friedrich Nietzsche",
    birth: 1844,
    death: 1900,
    approximate: false,
    region: "europe",
    placeLabel: "Germany / Basel / Turin",
    tradition: "existentialist",
    summary:
      "The philologist-turned-prophet who diagnosed the death of old values and demanded we create our own — with a hammer and a poet's pen.",
    coreIdeas: [
      "God is dead — and we must come to terms with what that empties",
      "Become who you are",
      "He who has a why can bear almost any how",
    ],
    questions: ["what-is-freedom", "how-should-i-live", "what-am-i"],
    works: ["Thus Spoke Zarathustra", "Beyond Good and Evil", "Genealogy of Morals"],
    relatedThinkers: ["kierkegaard", "de-beauvoir", "spinoza"],
    historicalContext:
      "Collapses, isolation and a late madness; his sister's distortion of his work shaped his reputation for decades — a warning about who gets to frame a legacy.",
    quote: {
      text: "He who has a why to live can bear almost any how.",
      source: "Twilight of the Idols, Maxims and Arrows §12",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Nietzsche" }],
  },
  {
    id: "de-beauvoir",
    name: "Simone de Beauvoir",
    birth: 1908,
    death: 1986,
    approximate: false,
    region: "europe",
    placeLabel: "Paris",
    tradition: "existentialist",
    summary:
      "The existentialist who showed that 'woman' is made, not born — and that freedom is real only when it is shared.",
    coreIdeas: [
      "One is not born, but rather becomes, a woman",
      "My freedom is bound to the freedom of others",
      "Ethics requires ambiguity: no formulas, only situations",
    ],
    questions: ["what-am-i", "what-is-freedom", "what-is-justice"],
    works: ["The Second Sex", "The Ethics of Ambiguity"],
    relatedThinkers: ["nietzsche", "arendt", "kierkegaard"],
    historicalContext:
      "Wrote The Second Sex (1949) from postwar Paris; it scandalized, sold, and began second-wave feminism's theoretical life.",
    quote: {
      text: "One is not born, but rather becomes, a woman.",
      source: "The Second Sex, introduction",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Simone de Beauvoir" }],
  },
  {
    id: "arendt",
    name: "Hannah Arendt",
    birth: 1906,
    death: 1975,
    approximate: false,
    region: "europe",
    placeLabel: "Germany → United States",
    tradition: "existentialist",
    summary:
      "The political thinker of totalitarianism, statelessness and 'the banality of evil' — thinking as the last defense against participating in horror.",
    coreIdeas: [
      "The banality of evil: harm done by thoughtlessness, not monsters",
      "Statelessness is the core political wound of the modern age",
      "Action and speech among plural people is what politics means",
    ],
    questions: ["what-is-justice", "what-is-freedom", "what-am-i"],
    works: ["The Origins of Totalitarianism", "Eichmann in Jerusalem", "The Human Condition"],
    relatedThinkers: ["de-beauvoir", "kant", "thucydides"],
    historicalContext:
      "Fled Nazi Germany, was interned in France, and rebuilt her life in New York — writing the century's clearest accounts of how politics fails.",
    quote: {
      text: "The sad truth is that most evil is done by people who never make up their minds to be good or evil.",
      source: "The Life of the Mind (thinking section)",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Hannah Arendt" }],
  },
  {
    id: "wittgenstein",
    name: "Ludwig Wittgenstein",
    birth: 1889,
    death: 1951,
    approximate: false,
    region: "europe",
    placeLabel: "Vienna → Cambridge",
    tradition: "modern",
    summary:
      "The engineer-turned-philosopher who wrote two systems that destroyed each other: first language as logic's picture, then language as lived use.",
    coreIdeas: [
      "The limits of my language mean the limits of my world",
      "Meaning is use, within a form of life",
      "Philosophy untangles; it does not build theories",
    ],
    questions: ["what-is-knowledge", "what-is-real", "what-am-i"],
    works: ["Tractatus Logico-Philosophicus", "Philosophical Investigations"],
    relatedThinkers: ["kant", "hume", "nagarjuna"],
    historicalContext:
      "Three brothers' suicides, two world wars, one austere chair at Cambridge — and the rare case of a thinker refuting his own early masterpiece in public.",
    quote: {
      text: "The limits of my language mean the limits of my world.",
      source: "Tractatus Logico-Philosophicus §5.6",
    },
    sources: [{ title: "Stanford Encyclopedia of Philosophy — Wittgenstein" }],
  },
];
